### ISSUE TITLE
Implement database

### ISSUE THREAD

**Issue by BSilton26** [Nathanllee1/Tabify#12]
Implement a MongoDB database to store User preferences and history using Spotify-provided id as identifier.

**Comment by BSilton26** [comment]
User prefs and history could be a future feature set. Focus on just having users stored.

**Comment by Nathanllee1** [comment]
https://developer.spotify.com/console/get-current-user/ get the user id with the access token on line 72 in server/index.js by running a get request to spotify

**Comment by BSilton26** [comment]
Completed for users, but must refactor for new functionality of storing tabs
