### ISSUE TITLE
Wrap scraper in Flask REST Api

### ISSUE THREAD

**Issue by Nathanllee1** [Nathanllee1/Tabify#40]
https://auth0.com/blog/developing-restful-apis-with-python-and-flask/

**Comment by Nathanllee1** [comment]
https://stackabuse.com/deploying-a-flask-application-to-heroku/

**Comment by doorlay** [comment]
Implemented here: https://github.com/doorlay/tabify-ug-scraper/commit/b716c6ddb1bd0f18f270eb78cc78c1fef4f4d6b7
